version: '3'
services:
  backend-main:
    build: 
      dockerfile: Dockerfile
      context: ./backend-main 
    volumes:
      - /app/node_modules 
      - ./backend-main:/app
    ports:
      - "3001:3000"
    environment:
      - DG_MESSAGE=Hello from local dev environment
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=
      - PGPORT=5432
  db-main:
    image: postgres:11
  webapp-main:
    build: 
      dockerfile: Dockerfile
      context: ./webapp-main 
    volumes:
      - /app/node_modules 
      - ./webapp-main:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true