name: backend-main-ci
on:
  push:
    paths:
    - 'backend-main/**'
defaults:
  run:
    working-directory: backend-main
jobs:
  ci:
    name: Build, push and deploy image
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build image and push to gcr.io
      uses: docker/build-push-action@v1
      with:
        path: backend-main
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: eu.gcr.io
        repository: digger-boot-267123/dg-myapp-backend-main
        tags: latest
    - name: Set up Google Cloud CLI
    uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    with:
      version: '290.0.1'
      service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
      project_id: digger-boot-267123
    - name: Deploy to Google Cloud Run
      run: |-
        gcloud run deploy "dg-myapp-backend-main" \
          --quiet \
          --region "europe-west1" \
          --image "eu.gcr.io/digger-boot-267123/dg-myapp-backend-main:latest" \
          --platform "managed" \
          --allow-unauthenticated
